CC = cc
CFLAGS = -Wall -Wextra -Werror

NAME = libft.a

SRCS := -f '*.c'

OBJS = $(SRCS:.c=.o)

all $(NAME)

$(NAME) : $(OBJS)
    ar rcs $(NAME) $(OBJS)

%.o: %.c libft.h
    $(CC) $(CFLAGS) -c $< -o $@

clean:
    rm -f ($OBJS)
fclean: 
    rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re